from handlers import client
from handlers import admin
from handlers import other
from handlers import emoji_bot
from handlers import moysklad
from handlers.admin_func import storage_reports
from handlers.admin_func import payments
from handlers.admin_func import report_range
from handlers.cass_func import report_close
from handlers.cass_func import take_my_salary
from handlers.cass_func import load_invoices
from handlers.cass_func import instructions
from handlers.cass_func import my_tasks
from handlers.mod_func import action_with_user
from handlers.mod_func import send_message
from handlers.mod_func import points
from handlers.mod_func import plans_of_sales
from handlers.admin_func import per_day
from handlers.admin_func import set_task
from handlers.admin_func import debts
from handlers.admin_func import per_month
from handlers.cass_func import zamena
from handlers.cass_func import defects
from handlers.admin_func import zarplata
from handlers.admin_func import upload_invoices
from handlers.admin_func import premies
from handlers.mod_func import set_salary
from handlers.mod_func import plans_of_product
from handlers.admin_func import set_fine
from handlers.admin_func import incassation
from handlers.mod_func import revision
from handlers.cass_func import load_expenses
from handlers.admin_func import upload_sheets
#from handlers.admin_func import upload_sheets_stocks
from handlers.admin_func import problems
from handlers.cass_func import report_open
from handlers.cass_func import local_revision
